### ISSUE TITLE
ftl2elm breaks with fluent 0.9+ installed

### ISSUE THREAD

**Issue by stasm** [elm-fluent/elm-fluent#15]
* elm-fluent version: 0.2.0
* Python version: 2.7.15rc1
* Operating System: Ubuntu (WSL)

### Description

The `fluent` dependency is listed as `fluent>=0.8.0`. `pip install elm-fluent` installs `fluent` 0.10.0, which breaks `elm-fluent`.

Both `fluent` 0.9.0 and 0.10.0 introduced changes to the AST. Please see the summary of the changes at https://github.com/projectfluent/python-fluent/releases. Notably, the `VariantName` node was removed. Variant keys can now be `Numbers` or `Identifiers`.

### What I Did

```
(@elm) $ Mozilla/fluent/elm-example -> ftl2elm
Traceback (most recent call last):
  File "/c/Users/stas/Mozilla/fluent/@elm/bin/ftl2elm", line 7, in <module>
    from elm_fluent.cli import main
  File "/c/Users/stas/Mozilla/fluent/@elm/local/lib/python2.7/site-packages/elm_fluent/cli.py", line 13, in <module>
    from .run import ErrorWhenMissing, FallbackToDefaultLocaleWhenMissing, run_compile
  File "/c/Users/stas/Mozilla/fluent/@elm/local/lib/python2.7/site-packages/elm_fluent/run.py", line 10, in <module>
    from .compiler import (
  File "/c/Users/stas/Mozilla/fluent/@elm/local/lib/python2.7/site-packages/elm_fluent/compiler.py", line 987, in <module>
    @compile_expr.register(ast.VariantName)
AttributeError: 'module' object has no attribute 'VariantName'
(@elm) $ Mozilla/fluent/elm-example ->    
```

`pip install fluent==0.8.0` fixed the issue.

**Comment by spookylukey** [comment]
Thanks for the report, fixed in 0.2.1 (just by specifying the dependency more closely)
